.\"                                      Hey, EMACS: -*- nroff -*-
.\"
.\" john-mmx.8 is copyright 2009 by
.\" David Paleino <d.paleino@gmail.com>
.\" This is free documentation, see the latest version of the GNU General
.\" Public License for copying conditions. There is NO warranty.
.TH JOHN 8 "January 18, 2009" john-mmx
.\" Please adjust this date whenever revising the manpage.
.SH NAME
john \- a tool to find weak passwords of your users
.SH SYNOPSIS
.B john
.RI [ options ]
password-files
.SH DESCRIPTION
\fBjohn-mmx\fP is the MMX-optimized version of \fBjohn\fP.
.PP
Please see \fBman john\fP to read a proper manual page.
.SH SEE ALSO
.BR john (8)
.SH AUTHOR
This manual page was written by David Paleino <d.paleino@gmail.com>.
